### ISSUE TITLE
Can't use with latest httpoison

### ISSUE THREAD

**Issue by OldhamMade** [bryanjos/keenex#7]
Can't use latest httpoison with current keenex, which causes issues with dependencies which require httpoison 1.3.

mix.exs:
```
  defp deps do
    [
      ...
      {:keenex, "~> 1.0"},
      {:httpoison, "~> 1.3"},
      ...
    ]
  end
```
`mix deps.get` result:
```
Failed to use "httpoison" (versions 1.3.0 and 1.3.1) because
  keenex (version 1.0.1) requires ~> 0.8
  mix.exs specifies ~> 1.3
```

**Comment by adamwiggall** [comment]
I have this issue too, can the dependency be updated?

**Comment by bryanjos** [comment]
Sorry I'm just seeing this. Yes. In the meantime, you should be able to do `{:httpoison, "~> 1.3", override: true}`

**Comment by OldhamMade** [comment]
@bryanjos sorry, I tried this before raising the ticket as it didn’t work for me.

**Comment by bryanjos** [comment]
I just pushed a new version. Let me know if it works out for you:
https://hex.pm/packages/keenex/1.1.0

**Comment by adamwiggall** [comment]
This is working for me. Thanks!
